{{- if .Values.controller.enabled }}
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
apiVersion: admissionregistration.k8s.io/v1
{{- else }}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "consul.fullname" . }}-controller-mutating-webhook-configuration
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: controller
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-proxydefaults
  failurePolicy: Fail
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
  sideEffects: None
  admissionReviewVersions:
    - "v1beta1"
    - "v1"
{{- end }}
  name: mutate-proxydefaults.consul.hashicorp.com
  rules:
    - apiGroups:
      - consul.hashicorp.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - proxydefaults
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-servicedefaults
  failurePolicy: Fail
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
  sideEffects: None
  admissionReviewVersions:
    - "v1beta1"
    - "v1"
{{- end }}
  name: mutate-servicedefaults.consul.hashicorp.com
  rules:
    - apiGroups:
      - consul.hashicorp.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - servicedefaults
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-serviceresolver
  failurePolicy: Fail
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
  sideEffects: None
  admissionReviewVersions:
    - "v1beta1"
    - "v1"
{{- end }}
  name: mutate-serviceresolver.consul.hashicorp.com
  rules:
    - apiGroups:
      - consul.hashicorp.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - serviceresolvers
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-servicerouter
  failurePolicy: Fail
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
  sideEffects: None
  admissionReviewVersions:
    - "v1beta1"
    - "v1"
{{- end }}
  name: mutate-servicerouter.consul.hashicorp.com
  rules:
    - apiGroups:
      - consul.hashicorp.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - servicerouters
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-servicesplitter
  failurePolicy: Fail
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
  sideEffects: None
  admissionReviewVersions:
    - "v1beta1"
    - "v1"
{{- end }}
  name: mutate-servicesplitter.consul.hashicorp.com
  rules:
    - apiGroups:
      - consul.hashicorp.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - servicesplitters
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-serviceintentions
  failurePolicy: Fail
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
  sideEffects: None
  admissionReviewVersions:
    - "v1beta1"
    - "v1"
{{- end }}
  name: mutate-serviceintentions.consul.hashicorp.com
  rules:
    - apiGroups:
      - consul.hashicorp.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - serviceintentions
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-ingressgateway
  failurePolicy: Fail
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
  sideEffects: None
  admissionReviewVersions:
    - "v1beta1"
    - "v1"
{{- end }}
  name: mutate-ingressgateway.consul.hashicorp.com
  rules:
    - apiGroups:
        - consul.hashicorp.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - ingressgateways
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-terminatinggateway
  failurePolicy: Fail
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
  sideEffects: None
  admissionReviewVersions:
    - "v1beta1"
    - "v1"
{{- end }}
  name: mutate-terminatinggateway.consul.hashicorp.com
  rules:
    - apiGroups:
        - consul.hashicorp.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - terminatinggateways
{{- end }}
